### ISSUE TITLE
Simple test program fails.

### ISSUE THREAD

**Issue by ole-tange** [xXCrash2BomberXx/Bython#1]
I cannot get it to work. `test.py`:
~~~
if True {
  print(3);
} else {
  print(4);
}
~~~
Run like:
~~~
$ python3 string.py test.py 
< invalid syntax (<unknown>, line 7)
<< 0.00014701997861266136s
~~~

**Comment by xXCrash2BomberXx** [comment]
That actually does cause a bug when you have the brace in front of the else statement so I will work on getting that bug fixed hopefully soon. Until then, use a newline after the closing brace to the if-statement and before the else-statement

**Comment by xXCrash2BomberXx** [comment]
Might've already fixed the issue. Just re-download the new `string.py` file and try it again. If it doesn't work, you can try using the optional `-o` argument to output the compiled Bython file to a specified file directory such as `-o out.py` which should run in standard python. Let me know if any other issues arise!
