### ISSUE TITLE
The 'utils' module hos not been loaded

### ISSUE THREAD

**Issue by ole-tange** [xXCrash2BomberXx/Bython#2]
I have removed the timer. It should really just be on for debugging.

But even with that removed I get more output than expected:

~~~
$ bython  test.py
The 'utils' module hos not been loaded
3
~~~

**Comment by xXCrash2BomberXx** [comment]
Easy 'fix'. In the `string.py` file, on line 4, the statement `print("The 'utils' module hos not been loaded")` can just be replaced with `pass` if you don't want the message. If you want to completely ignore the `utils.py` file and not even have it try opening it, delete lines 1 through 4. I'm going to implement your suggestion of the timer only being used in debugging so I should have an update uploaded shortly!

**Comment by xXCrash2BomberXx** [comment]
Okay, all fixed (hopefully)! I appreciate the continued usage and recommendations!
